// <auto-generated />
namespace OnBoardingTask.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class KeysOnBoarding_Proj1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KeysOnBoarding_Proj1));
        
        string IMigrationMetadata.Id
        {
            get { return "201809130340138_KeysOnBoarding_Proj1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
